# Module for locating OpenCV.
#
# Customizable variables:
#   OPENCV_ROOT_DIR
#     Specifies the OpenCV root directory.
# Read-only variables:
#   OPENCV_FOUND
#     Indicates whether the library has been found.
#
#   OPENCV_INCLUDE_DIRS
#     Specifies to the OpenCV include directory.
#
#   OPENCV_LIBRARIES
#     Specifies the OpenCV libraries that should be passed to
#     target_link_libararies.

INCLUDE (FindPackageHandleStandardArgs)

IF (CMAKE_VERSION VERSION_GREATER 2.8.7)
  SET (_OPENCV_CHECK_COMPONENTS FALSE)
ELSE (CMAKE_VERSION VERSION_GREATER 2.8.7)
  SET (_OPENCV_CHECK_COMPONENTS TRUE)
ENDIF (CMAKE_VERSION VERSION_GREATER 2.8.7)

message("trying to find local OpenCV..")

FIND_PATH( OPENCV_INCLUDE_DIR opencv2/core.hpp
		"${OPENCV_ROOT_DIR}/include"
		DOC "The directory where opencv2/core.hpp resides")

if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
set(OPENCV_LIBRARIES "${OPENCV_ROOT_DIR}/lib/libopencv_calib3d.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_core.so")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cuda.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudaarithm.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudabgsegm.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudacodec.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudafeatures2d.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudafilters.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudaimgproc.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudalegacy.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudaoptflow.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudastereo.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudawarping.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_cudev.a")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_features2d.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_flann.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_highgui.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_imgcodecs.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_imgproc.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_ml.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_objdetect.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_photo.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_shape.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_stitching.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_superres.so")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_traincascade.lib")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_ts.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_video.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_videoio.so")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libopencv_videostab.so")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libIlmImf.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libjasper.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libjpeg.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libpng.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libtiff.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libtiffxx.a")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libwebp.lib")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/libz.a")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" dl rt tiff jpeg png jasper z avformat avcodec avutil swscale "gstreamer-0.10" "glib-2.0" "gobject-2.0" "gstapp-0.10" "gstbase-0.10" "gstvideo-0.10" "gstpbutils-0.10" "gstnet-0.10" "gstriff-0.10" "bz2")
set(OPENCV_DEBUG_LIBRARIES OPENCV_LIBRARIES)
else()		
set(OPENCV_LIBRARIES "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_core300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_calib3d300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_features2d300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_flann300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_highgui300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_imgcodecs300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_imgproc300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_ml300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_objdetect300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_photo300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_shape300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_stitching300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_superres300.lib")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_traincascade.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_ts300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_hal300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_video300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_videoio300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_videostab300.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/IlmImf.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libjasper.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libjpeg.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libpng.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libtiff.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libwebp.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/zlib.lib")
#set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" PARENT_SCOPE)

set(OPENCV_DEBUG_LIBRARIES "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_core300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_calib3d300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_features2d300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_flann300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_highgui300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_imgcodecs300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_imgproc300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_ml300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_objdetect300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_photo300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_shape300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_stitching300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_superres300d.lib")
#set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_traincascaded.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_ts300d.lib")
set(OPENCV_LIBRARIES "${OPENCV_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_hal300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_video300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_videoio300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/opencv_videostab300d.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/IlmImfd.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libjasperd.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libjpegd.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libpngd.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libtiffd.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/libwebpd.lib")
set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" "${OPENCV_ROOT_DIR}/lib/x64/windows/zlibd.lib")
#set(OPENCV_DEBUG_LIBRARIES "${OPENCV_DEBUG_LIBRARIES}" PARENT_SCOPE)
endif()

IF (OPENCV_INCLUDE_DIR)
	SET( OPENCV_FOUND 1 CACHE STRING "Set to 1 if OpenCV is found, 0 otherwise")
	message("Local OpenCV found!")
ELSE (OPENCV_INCLUDE_DIR)
	SET( OPENCV_FOUND 0 CACHE STRING "Set to 1 if OpenCV is found, 0 otherwise")
	message("Local OpenCV not found!")
ENDIF (OPENCV_INCLUDE_DIR)

MARK_AS_ADVANCED( OPENCV_INCLUDE_DIR )
MARK_AS_ADVANCED( OPENCV_LIBRARIES )
MARK_AS_ADVANCED( OPENCV_DEBUG_LIBRARIES )
